# #####################################################################
# Automatically generated by qmake (2.01a) ?? 18. ??? 22:44:06 2012
# #####################################################################
TEMPLATE = app
TARGET = test
CONFIG += console
DEPENDPATH += .
INCLUDEPATH += . \
    ..

# Input
HEADERS += ../tools/metadata.h \
    pch.h \
    PrintData.h \
    struct.h \
    test.h \
    treater.h

SOURCES += test.cpp \
    test1.cpp
